# Generated by Django 4.0.6 on 2022-08-10 02:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sports', '0001_initial'),
        ('programming', '0002_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('consec_equipo', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('fecha_resol', models.DateField(default=datetime.datetime.today)),
                ('deporte', models.ForeignKey(default='01', on_delete=django.db.models.deletion.CASCADE, to='sports.deporte')),
                ('empleado', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='users.empleado', verbose_name='Entrenador')),
            ],
        ),
        migrations.CreateModel(
            name='MiembroEquipo',
            fields=[
                ('itemMiembro', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('equipo', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='teams.equipo')),
                ('estudiante', models.ForeignKey(default='20221020001', on_delete=django.db.models.deletion.CASCADE, to='users.estudiante', verbose_name='Pertenece')),
            ],
        ),
        migrations.CreateModel(
            name='AsisMiembroEquipo',
            fields=[
                ('con_miembro_equipo', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('miembro_equipo', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='teams.miembroequipo', verbose_name='Miembro equipo')),
                ('programacion', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='programming.programacion')),
            ],
        ),
    ]
