# Generated by Django 4.0.6 on 2022-08-09 22:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AsisMiembroEquipo',
            fields=[
                ('con_miembro_equipo', models.AutoField(max_length=4, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('consec_equipo', models.AutoField(max_length=3, primary_key=True, serialize=False, unique=True)),
                ('fecha_resol', models.DateField(default=datetime.datetime.today)),
            ],
        ),
        migrations.CreateModel(
            name='MiembroEquipo',
            fields=[
                ('itemMiembro', models.AutoField(max_length=3, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
