# Generated by Django 4.0.6 on 2022-07-25 03:56

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('cod_estudiante', models.CharField(max_length=11, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(default='no registra', max_length=30)),
                ('apellido', models.CharField(default='no registra', max_length=30)),
                ('fecha_inscripcion', models.DateField(default=datetime.datetime.today)),
                ('fecha_nacimiento', models.DateField(default=datetime.datetime.today)),
                ('correo', models.EmailField(default='example@example.com', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('rol', models.DecimalField(decimal_places=1, max_digits=4, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id_tipo_documento', models.SmallIntegerField(primary_key=True, serialize=False, unique=True)),
                ('abreviacion', models.CharField(max_length=5)),
                ('desc_tipo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('cod_persona', models.CharField(max_length=11, primary_key=True, serialize=False, unique=True)),
                ('numero_documento', models.CharField(default='00000000000', max_length=11)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('id_tipo_documento', models.ForeignKey(default='no registra', on_delete=django.db.models.deletion.CASCADE, to='users.tipodocumento')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
