# Generated by Django 4.0.6 on 2022-08-09 15:32

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('cod_empleado', models.CharField(default='0001', max_length=4, primary_key=True, serialize=False, unique=True)),
                ('nom_empleado', models.CharField(default='', max_length=20)),
                ('apell_empleado', models.CharField(default='', max_length=20)),
                ('fecha_registro', models.DateField(default=datetime.datetime.today)),
                ('correo_ud', models.EmailField(default='example@udistrital.edu.co', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('cod_estu', models.CharField(default='20221020001', max_length=12, primary_key=True, serialize=False, unique=True)),
                ('nom_estu', models.CharField(default='', max_length=30)),
                ('apell_estu', models.CharField(default='', max_length=30)),
                ('fecha_reg_estu', models.DateField(default=datetime.datetime.today)),
                ('fecha_nac_estu', models.DateField(default=datetime.datetime.today)),
                ('correo_ud_estu', models.EmailField(default='example@correo.udistrital.edu.co', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='EstudianteUser',
            fields=[
                ('cod_estudiante', models.CharField(max_length=11, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(default='no registra', max_length=30)),
                ('apellido', models.CharField(default='no registra', max_length=30)),
                ('fecha_inscripcion', models.DateField(default=datetime.datetime.today)),
                ('fecha_nacimiento', models.DateField(default=datetime.datetime.today)),
                ('correo_institucional', models.EmailField(default='example@correo.udistrital.edu.co', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.CharField(default='0', max_length=1, primary_key=True, serialize=False)),
                ('desc_rol', models.CharField(default='', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id_tipo_documento', models.SmallIntegerField(primary_key=True, serialize=False, unique=True)),
                ('abreviacion', models.CharField(max_length=5)),
                ('desc_tipo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('numero_documento', models.CharField(default='00000000000', max_length=11, primary_key=True, serialize=False)),
                ('correo', models.EmailField(default='example@example.com', max_length=40)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='users/picture')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('id_tipo_documento', models.ForeignKey(default='no registra', on_delete=django.db.models.deletion.CASCADE, to='users.tipodocumento')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
