# Generated by Django 4.0.6 on 2022-08-09 16:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsisResponsable',
            fields=[
                ('consec_asis_responsable', models.AutoField(max_length=4, primary_key=True, serialize=False, unique=True)),
                ('fecha_asis_responsable', models.DateField(default=datetime.datetime.today)),
                ('hora_asis_responsable', models.DateField(default=datetime.datetime.today)),
            ],
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id_cargo', models.CharField(default='01', max_length=2, primary_key=True, serialize=False, unique=True)),
                ('desc_cargo', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='EmpleadoCargo',
            fields=[
                ('consec', models.AutoField(max_length=3, primary_key=True, serialize=False, unique=True)),
                ('fecha_cargo', models.DateField(default=datetime.datetime.today)),
                ('fecha_fin_cargo', models.DateField(default=datetime.datetime.today)),
            ],
        ),
        migrations.CreateModel(
            name='Responsable',
            fields=[
                ('consec_responsable', models.AutoField(max_length=4, primary_key=True, serialize=False, unique=True)),
                ('fecha_inicio', models.DateField(default=datetime.datetime.today)),
                ('fecha_fin', models.DateField(default=datetime.datetime.today)),
            ],
        ),
    ]
