# Generated by Django 4.0.6 on 2022-08-09 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_asisresponsable_cargo_empleadocargo_responsable'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudianteuser',
            name='identificacion',
            field=models.OneToOneField(default='00000000000', on_delete=django.db.models.deletion.CASCADE, to='users.persona'),
        ),
    ]
