# Generated by Django 4.0.6 on 2022-08-09 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id_actividad', models.CharField(default='01', max_length=2, primary_key=True, serialize=False, unique=True)),
                ('desc_actividad', models.CharField(default='', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Dia',
            fields=[
                ('id_dia', models.CharField(default='1', max_length=1, primary_key=True, serialize=False, unique=True)),
                ('nom_dia', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Espacio',
            fields=[
                ('cod_espacio', models.CharField(default='01', max_length=2, primary_key=True, serialize=False, unique=True)),
                ('nom_espacio', models.CharField(default='', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Hora',
            fields=[
                ('id_hora', models.CharField(default='01', max_length=2, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='inscritoPractLibre',
            fields=[
                ('consec_practica', models.AutoField(max_length=4, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id_periodo', models.CharField(default='00001', max_length=5, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('consec_prestamo', models.AutoField(max_length=4, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Programacion',
            fields=[
                ('consec_program', models.AutoField(max_length=4, primary_key=True, serialize=False, unique=True)),
                ('cupo', models.IntegerField(default='001', max_length=3)),
                ('no_inscritos', models.IntegerField(default='001', max_length=3, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoEspacio',
            fields=[
                ('id_tipo_espacio', models.CharField(default='01', max_length=2, primary_key=True, serialize=False, unique=True)),
                ('desc_tipo_espacio', models.CharField(default='', max_length=30)),
            ],
        ),
    ]
