# Generated by Django 4.0.6 on 2022-08-10 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id_actividad', models.CharField(default='01', max_length=2, primary_key=True, serialize=False, unique=True)),
                ('desc_actividad', models.CharField(default='', max_length=30, verbose_name='Actividad')),
            ],
        ),
        migrations.CreateModel(
            name='Dia',
            fields=[
                ('id_dia', models.CharField(default='1', max_length=1, primary_key=True, serialize=False, unique=True, verbose_name='N° Día')),
                ('nom_dia', models.CharField(default='', max_length=10, verbose_name='Día')),
            ],
        ),
        migrations.CreateModel(
            name='Espacio',
            fields=[
                ('cod_espacio', models.CharField(default='01', max_length=2, primary_key=True, serialize=False, unique=True)),
                ('nom_espacio', models.CharField(default='', max_length=30, verbose_name='Espacio')),
            ],
        ),
        migrations.CreateModel(
            name='Hora',
            fields=[
                ('id_hora', models.CharField(default='01', max_length=2, primary_key=True, serialize=False, unique=True)),
                ('hora', models.TimeField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='InscritoPractLibre',
            fields=[
                ('consec_practica', models.AutoField(primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id_periodo', models.CharField(default='00001', max_length=5, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('consec_prestamo', models.AutoField(primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoEspacio',
            fields=[
                ('id_tipo_espacio', models.CharField(default='01', max_length=2, primary_key=True, serialize=False, unique=True)),
                ('desc_tipo_espacio', models.CharField(default='', max_length=30, verbose_name='Descripción')),
            ],
        ),
        migrations.CreateModel(
            name='Programacion',
            fields=[
                ('consec_program', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('cupo', models.IntegerField(default='001', verbose_name='Cupos')),
                ('no_inscritos', models.IntegerField(default='001', null=True, verbose_name='N° Inscritos')),
                ('actividad', models.ForeignKey(default='01', on_delete=django.db.models.deletion.CASCADE, to='programming.actividad')),
            ],
        ),
    ]
