# Generated by Django 4.0.6 on 2022-08-10 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sports', '0001_initial'),
        ('programming', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='programacion',
            name='deporte_fk',
            field=models.ForeignKey(default='01', on_delete=django.db.models.deletion.CASCADE, to='sports.deporte'),
        ),
        migrations.AddField(
            model_name='programacion',
            name='dia',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='programming.dia'),
        ),
        migrations.AddField(
            model_name='programacion',
            name='espacio',
            field=models.ForeignKey(default='01', null=True, on_delete=django.db.models.deletion.CASCADE, to='programming.espacio'),
        ),
        migrations.AddField(
            model_name='programacion',
            name='hora_inicio',
            field=models.ForeignKey(default='01', on_delete=django.db.models.deletion.CASCADE, to='programming.hora', verbose_name='Hora inicio'),
        ),
        migrations.AddField(
            model_name='programacion',
            name='periodo',
            field=models.ForeignKey(default='00001', on_delete=django.db.models.deletion.CASCADE, to='programming.periodo'),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='asis_responsable',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='users.asisresponsable', verbose_name='Asistente responsable'),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='elemento_deportivo',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='sports.elementodeportivo'),
        ),
        migrations.AddField(
            model_name='inscritopractlibre',
            name='empleado',
            field=models.ForeignKey(blank=True, default='0001', null=True, on_delete=django.db.models.deletion.CASCADE, to='users.empleado'),
        ),
        migrations.AddField(
            model_name='inscritopractlibre',
            name='estudiante',
            field=models.ForeignKey(default='20221020001', null=True, on_delete=django.db.models.deletion.CASCADE, to='users.estudiante'),
        ),
        migrations.AddField(
            model_name='inscritopractlibre',
            name='programacion',
            field=models.ForeignKey(default='1', null=True, on_delete=django.db.models.deletion.CASCADE, to='programming.programacion'),
        ),
        migrations.AddField(
            model_name='espacio',
            name='tipo_espacio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programming.tipoespacio', verbose_name='Tipo de espacio'),
        ),
    ]
