--
-- Add field deporte_fk to programacion
--
ALTER TABLE "PROGRAMMING_PROGRAMACION" ADD "DEPORTE_FK_ID" NVARCHAR2(2) DEFAULT '01' NOT NULL CONSTRAINT "PROGRAMMI_DEPORTE_F_B5B49465_F" REFERENCES "SPORTS_DEPORTE"("ID_DEPORTE") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "PROGRAMMING_PROGRAMACION" MODIFY "DEPORTE_FK_ID" DEFAULT NULL;
--
-- Add field dia to programacion
--
ALTER TABLE "PROGRAMMING_PROGRAMACION" ADD "DIA_ID" NVARCHAR2(1) DEFAULT '1' NOT NULL CONSTRAINT "PROGRAMMI_DIA_ID_6195E384_F" REFERENCES "PROGRAMMING_DIA"("ID_DIA") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "PROGRAMMING_PROGRAMACION" MODIFY "DIA_ID" DEFAULT NULL;
--
-- Add field espacio to programacion
--
ALTER TABLE "PROGRAMMING_PROGRAMACION" ADD "ESPACIO_ID" NVARCHAR2(2) DEFAULT '01' NULL CONSTRAINT "PROGRAMMI_ESPACIO_I_E00F3239_F" REFERENCES "PROGRAMMING_ESPACIO"("COD_ESPACIO") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "PROGRAMMING_PROGRAMACION" MODIFY "ESPACIO_ID" DEFAULT NULL;
--
-- Add field hora_inicio to programacion
--
ALTER TABLE "PROGRAMMING_PROGRAMACION" ADD "HORA_INICIO_ID" NVARCHAR2(2) DEFAULT '01' NOT NULL CONSTRAINT "PROGRAMMI_HORA_INIC_792E12D8_F" REFERENCES "PROGRAMMING_HORA"("ID_HORA") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "PROGRAMMING_PROGRAMACION" MODIFY "HORA_INICIO_ID" DEFAULT NULL;
--
-- Add field periodo to programacion
--
ALTER TABLE "PROGRAMMING_PROGRAMACION" ADD "PERIODO_ID" NVARCHAR2(5) DEFAULT '00001' NOT NULL CONSTRAINT "PROGRAMMI_PERIODO_I_BB23BAB8_F" REFERENCES "PROGRAMMING_PERIODO"("ID_PERIODO") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "PROGRAMMING_PROGRAMACION" MODIFY "PERIODO_ID" DEFAULT NULL;
--
-- Add field asis_responsable to prestamo
--
ALTER TABLE "PROGRAMMING_PRESTAMO" ADD "ASIS_RESPONSABLE_ID" NUMBER(11) DEFAULT 1 NOT NULL CONSTRAINT "PROGRAMMI_ASIS_RESP_8DF45299_F" REFERENCES "USERS_ASISRESPONSABLE"("CONSEC_ASIS_RESPONSABLE") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "PROGRAMMING_PRESTAMO" MODIFY "ASIS_RESPONSABLE_ID" DEFAULT NULL;
--
-- Add field elemento_deportivo to prestamo
--
ALTER TABLE "PROGRAMMING_PRESTAMO" ADD "ELEMENTO_DEPORTIVO_ID" NUMBER(11) DEFAULT 1 NOT NULL CONSTRAINT "PROGRAMMI_ELEMENTO__255D674C_F" REFERENCES "SPORTS_ELEMENTODEPORTIVO"("CONSEC_ELEMENTO") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "PROGRAMMING_PRESTAMO" MODIFY "ELEMENTO_DEPORTIVO_ID" DEFAULT NULL;
--
-- Add field empleado to inscritopractlibre
--
ALTER TABLE "PROGRAMMING_INSCRITOPRACTLIBRE" ADD "EMPLEADO_ID" NVARCHAR2(4) DEFAULT '0001' NULL CONSTRAINT "PROGRAMMI_EMPLEADO__7A2300D0_F" REFERENCES "USERS_EMPLEADO"("COD_EMPLEADO") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "PROGRAMMING_INSCRITOPRACTLIBRE" MODIFY "EMPLEADO_ID" DEFAULT NULL;
--
-- Add field estudiante to inscritopractlibre
--
ALTER TABLE "PROGRAMMING_INSCRITOPRACTLIBRE" ADD "ESTUDIANTE_ID" NVARCHAR2(12) DEFAULT '20221020001' NULL CONSTRAINT "PROGRAMMI_ESTUDIANT_BC7AC244_F" REFERENCES "USERS_ESTUDIANTE"("COD_ESTU") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "PROGRAMMING_INSCRITOPRACTLIBRE" MODIFY "ESTUDIANTE_ID" DEFAULT NULL;
--
-- Add field programacion to inscritopractlibre
--
ALTER TABLE "PROGRAMMING_INSCRITOPRACTLIBRE" ADD "PROGRAMACION_ID" NUMBER(11) DEFAULT 1 NULL CONSTRAINT "PROGRAMMI_PROGRAMAC_FA5EB95D_F" REFERENCES "PROGRAMMING_PROGRAMACION"("CONSEC_PROGRAM") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "PROGRAMMING_INSCRITOPRACTLIBRE" MODIFY "PROGRAMACION_ID" DEFAULT NULL;
--
-- Add field tipo_espacio to espacio
--
ALTER TABLE "PROGRAMMING_ESPACIO" ADD "TIPO_ESPACIO_ID" NVARCHAR2(2) NOT NULL CONSTRAINT "PROGRAMMI_TIPO_ESPA_B34D022F_F" REFERENCES "PROGRAMMING_TIPOESPACIO"("ID_TIPO_ESPACIO") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "PROGRAMMIN_DEPORTE_FK_B5B49465" ON "PROGRAMMING_PROGRAMACION" ("DEPORTE_FK_ID");
CREATE INDEX "PROGRAMMIN_DIA_ID_6195E384" ON "PROGRAMMING_PROGRAMACION" ("DIA_ID");
CREATE INDEX "PROGRAMMIN_ESPACIO_ID_E00F3239" ON "PROGRAMMING_PROGRAMACION" ("ESPACIO_ID");
CREATE INDEX "PROGRAMMIN_HORA_INICI_792E12D8" ON "PROGRAMMING_PROGRAMACION" ("HORA_INICIO_ID");
CREATE INDEX "PROGRAMMIN_PERIODO_ID_BB23BAB8" ON "PROGRAMMING_PROGRAMACION" ("PERIODO_ID");
CREATE INDEX "PROGRAMMIN_ASIS_RESPO_8DF45299" ON "PROGRAMMING_PRESTAMO" ("ASIS_RESPONSABLE_ID");
CREATE INDEX "PROGRAMMIN_ELEMENTO_D_255D674C" ON "PROGRAMMING_PRESTAMO" ("ELEMENTO_DEPORTIVO_ID");
CREATE INDEX "PROGRAMMIN_EMPLEADO_I_7A2300D0" ON "PROGRAMMING_INSCRITOPRACTLIBRE" ("EMPLEADO_ID");
CREATE INDEX "PROGRAMMIN_ESTUDIANTE_BC7AC244" ON "PROGRAMMING_INSCRITOPRACTLIBRE" ("ESTUDIANTE_ID");
CREATE INDEX "PROGRAMMIN_PROGRAMACI_FA5EB95D" ON "PROGRAMMING_INSCRITOPRACTLIBRE" ("PROGRAMACION_ID");
CREATE INDEX "PROGRAMMIN_TIPO_ESPAC_B34D022F" ON "PROGRAMMING_ESPACIO" ("TIPO_ESPACIO_ID");
