# Generated by Django 4.0.6 on 2022-08-10 15:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('programming', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id_estado', models.CharField(default='01', max_length=2, primary_key=True, serialize=False, unique=True)),
                ('desc_estado', models.CharField(default='', max_length=20, verbose_name='Estado')),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id_marca', models.CharField(default='01', max_length=2, primary_key=True, serialize=False, unique=True)),
                ('nom_marca', models.CharField(default='', max_length=20, verbose_name='Nombre marca')),
            ],
        ),
        migrations.CreateModel(
            name='TipoElemento',
            fields=[
                ('id_tipo_elemento', models.CharField(default='01', max_length=2, primary_key=True, serialize=False, unique=True)),
                ('desc_tipo_elemento', models.CharField(default='', max_length=40, verbose_name='Tipo elemento')),
            ],
        ),
        migrations.CreateModel(
            name='ElementoDeportivo',
            fields=[
                ('consec_elemento', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('fecha_registro', models.DateField(default=datetime.datetime.today)),
                ('espacio', models.ForeignKey(default='01', null=True, on_delete=django.db.models.deletion.CASCADE, to='programming.espacio')),
                ('estado', models.ForeignKey(default='01', on_delete=django.db.models.deletion.CASCADE, to='sports.estado')),
                ('marca', models.ForeignKey(default='01', on_delete=django.db.models.deletion.CASCADE, to='sports.marca')),
                ('tipo_elemento', models.ForeignKey(default='01', on_delete=django.db.models.deletion.CASCADE, to='sports.tipoelemento')),
            ],
        ),
        migrations.CreateModel(
            name='Deporte',
            fields=[
                ('id_deporte', models.CharField(default='01', max_length=2, primary_key=True, serialize=False, unique=True)),
                ('nom_deporte', models.CharField(default='', max_length=20, verbose_name='Nombre deporte')),
                ('espacio', models.ManyToManyField(default='01', to='programming.espacio')),
                ('tipo_elemento', models.ManyToManyField(default='01', to='sports.tipoelemento')),
            ],
        ),
    ]
