# Generated by Django 4.0.6 on 2022-08-09 22:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deporte',
            fields=[
                ('id_deporte', models.CharField(default='01', max_length=2, primary_key=True, serialize=False, unique=True)),
                ('nom_deporte', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ElementoDeportivo',
            fields=[
                ('consec_elemento', models.AutoField(max_length=5, primary_key=True, serialize=False, unique=True)),
                ('fecha_registro', models.DateField(default=datetime.datetime.today)),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id_estado', models.CharField(default='01', max_length=2, primary_key=True, serialize=False, unique=True)),
                ('desc_estado', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id_marca', models.CharField(default='01', max_length=2, primary_key=True, serialize=False, unique=True)),
                ('nom_marca', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TipoElemento',
            fields=[
                ('id_tipo_elemento', models.CharField(default='01', max_length=2, primary_key=True, serialize=False, unique=True)),
                ('desc_tipo_elemento', models.CharField(default='', max_length=40)),
            ],
        ),
    ]
