# Generated by Django 4.0.6 on 2022-08-09 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programming', '0001_initial'),
        ('sports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deporte',
            name='programacio_fk',
            field=models.ManyToManyField(to='programming.programacion'),
        ),
    ]
