# Generated by Django 4.0.6 on 2022-08-10 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programming', '0001_initial'),
        ('sports', '0002_deporte_programacio_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deporte',
            name='programacio_fk',
        ),
        migrations.AddField(
            model_name='deporte',
            name='programacion',
            field=models.ManyToManyField(default='', to='programming.programacion'),
        ),
        migrations.AddField(
            model_name='deporte',
            name='tipo_elemento',
            field=models.ManyToManyField(default='', to='sports.tipoelemento'),
        ),
        migrations.AddField(
            model_name='elementodeportivo',
            name='estado',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='sports.estado'),
        ),
        migrations.AddField(
            model_name='elementodeportivo',
            name='marca',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='sports.marca'),
        ),
        migrations.AddField(
            model_name='elementodeportivo',
            name='tipo_elemento',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='sports.tipoelemento'),
        ),
        migrations.AlterField(
            model_name='deporte',
            name='nom_deporte',
            field=models.CharField(default='', max_length=20, verbose_name='Nombre deporte'),
        ),
        migrations.AlterField(
            model_name='marca',
            name='nom_marca',
            field=models.CharField(default='', max_length=20, verbose_name='Nombre marca'),
        ),
    ]
